apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubearmor-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/safeer-accuknox/accuknox-cwpp-kspm-gitops.git
    targetRevision: HEAD
    path: accuknox/kubearmor-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: kubearmor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true