apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubearmor-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/safeer-accuknox/accuknox-cwpp-kspm-gitops.git
    targetRevision: HEAD
    path: accuknox/kubearmor-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true