apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: accuknox-kiem-job
  namespace: argocd
stringData:
  url: public.ecr.aws/k9v9d5v2
  project: default
  name: kiem-job
  type: helm
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: accuknox-cis-k8s-job
  namespace: argocd
stringData:
  url: public.ecr.aws/k9v9d5v2
  project: default
  name: cis-k8s-job
  type: helm
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: accuknox-k8s-risk-assessment-job
  namespace: argocd
stringData:
  url: public.ecr.aws/k9v9d5v2
  project: default
  name: k8s-risk-assessment-job
  type: helm
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: accuknox-agents
  namespace: argocd
stringData:
  url: registry-1.docker.io/accuknox
  project: default
  name: accuknox-agents
  type: helm
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: kubearmor-operator
  namespace: argocd
stringData:
  url: https://kubearmor.github.io/charts
  project: default
  name: kubearmor-operator
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: accuknox-cwpp-kspm-gitops
  namespace: argocd
stringData:
  url: https://github.com/safeer-accuknox/accuknox-cwpp-kspm-gitops
  project: default
  name: accuknox-cwpp-kspm-gitops
  type: git
---